version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl --silent --show-error --location --fail --retry 3 --output sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip -o sonar-scanner.zip -d /opt/sonar-scanner
      - rm sonar-scanner.zip

  build:
    commands:
      - echo "sonar.host.url=http://184.73.73.251:9000" >> /opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
      - /opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
        -Dsonar.login=squ_30b091253eb3e039259a733fe26264317b95755b
        -Dsonar.projectKey=com.company:MyProject
        -Dsonar.projectName=Project
        -Dsonar.projectVersion=1.0
        -Dsonar.sources=.


          
        
     
